### ISSUE TITLE
[ISAAC-486] Upgrade to supabase-js v2

### ISSUE THREAD

**Issue by eimenhmdt** [aietal/isaac#20]
<sub>From [SyncLinear.com](https://synclinear.com) | [ISAAC-486](https://linear.app/isaac-editor/issue/ISAAC-486/upgrade-to-supabase-js-v2)</sub>

Update all instances of JS Supabase sdk in our application from the currently used supabase-js v1 to the supabase-js v2. This upgrade will involve modifying existing Supabase integrations to ensure compatibility with the latest version, addressing any breaking changes, and potentially leveraging new features and improvements offered in v2.

**Comment by jkcs** [comment]
Is this issue still unresolved? Can I be assigned to handle this?
