### ISSUE TITLE
[ISAAC-489] Chat seems to be generating before a message has been sent and can't be stopped

### ISSUE THREAD

**Issue by eimenhmdt** [aietal/isaac#26]
![CleanShot 2023-12-03 at 02.31.27@2x.png](https://uploads.linear.app/7c90c08b-6763-457d-8a5a-ed4ea2f3c43b/4181fc36-a415-4258-8123-74b7d1cee014/7ff57a55-44f3-4c25-8b2b-836ba57d5a9e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdjOTBjMDhiLTY3NjMtNDU3ZC04YTVhLWVkNGVhMmYzYzQzYi80MTgxZmMzNi1hNDE1LTQyNTgtODEyMy03NGI3ZDFjZWUwMTQvN2ZmNTdhNTUtNDRmMy00YzI1LThiMmItODM2YmE1N2Q1YTllIiwiaWF0IjoxNzAxNTU2MzUyLCJleHAiOjE3MDE2NDI3NTJ9.9GbTbUxFCeFlkIueMZjUWTZPaP_HvB7rhanqwFaBBG8)

<sub>From [SyncLinear.com](https://synclinear.com) | [ISAAC-489](https://linear.app/isaac-editor/issue/ISAAC-489/chat-seems-to-be-generating-before-a-message-has-been-sent-and-cant-be)</sub>

**Comment by ibrahimyaacob92** [comment]
@eimenhmdt this PR allow user to stop generation:
https://github.com/aietal/isaac/pull/17

**Comment by ibrahimyaacob92** [comment]
Okay @eimenhmdt can you share how do this ?
"Chat seems to be generating before a message has been sent and can't be stopped"
