### ISSUE TITLE
[ISAAC-490] Add LiteLLM to Python API and refactor Next.js AI Routes to Use LiteLLM Through Python API Instead of Direct OpenAI API Calls

### ISSUE THREAD

**Issue by eimenhmdt** [aietal/isaac#28]
Currently, we use direct OpenAI API calls from the next.js app for our AI related APIs. Implementing LiteLLM and and running the OpenAI API calls through litellm from our fastapi app will help us

Currently, we use direct OpenAI API calls from the next.js app for our AI related APIs. Implementing LiteLLM and and running the OpenAI API calls through litellm from our fastapi app will help us We aim to standardize our LLM API calls by routing them through LiteLLM. This will enable us to utilize a variety of LLM providers (Bedrock, Huggingface, Cohere, TogetherAI, Azure, OpenAI, etc.) while maintaining an OpenAI-compatible interface.

Key objectives include:

1. **Translation of Inputs:** Adapt input parameters to match the requirements of each provider's completion and embedding endpoints.
2. **Output Consistency:** Ensure that text responses are reliably accessed at `['choices'][0]['message']['content']`.
3. **Exception Handling:** Map provider-specific exceptions to OpenAI's exception format for uniform error handling.
4. **Load Balancing:** Efficiently distribute a high volume of requests (1k+ requests/second) across multiple deployments, including Azure and OpenAI.
5. **Resilience Measures:** Implement fallback mechanisms and retry strategies to maintain service continuity.

Benefits:

* **Model Diversity:** Facilitates the integration of additional models, offering a broader range to our users.
* **API Call Oversight:** Provides a consolidated view of API calls for better management.
* **Unified API:** Establishes a single FastAPI interface for all LLM interactions, enhancing maintainability and scalability.

Implementation Requirements:

* Configure LiteLLM within our FastAPI framework.
* Develop necessary FastAPI endpoints to handle LLM requests.
* Refactor the existing direct OpenAI API calls in our Next.js application to route through the new FastAPI endpoints.

This update will necessitate thorough testing to ensure seamless integration and performance across all systems.

Link to litellm: [https://docs.litellm.ai/docs/completion/reliable_completions#fallbacks-1](https://docs.litellm.ai/docs/completion/reliable_completions#fallbacks-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [ISAAC-490](https://linear.app/isaac-editor/issue/ISAAC-490/add-litellm-to-python-api-and-refactor-nextjs-ai-routes-to-use-litellm)</sub>

**Comment by rishi-raj-jain** [comment]
Please assign this to me?

**Comment by eimenhmdt** [comment]
ok let's go @rishi-raj-jain

**Comment by rishi-raj-jain** [comment]
Sure thing
