### ISSUE TITLE
[ISAAC-437] Optimize PDF Loading Performance by Implementing Linearized Loading

### ISSUE THREAD

**Issue by eimenhmdt** [aietal/isaac#30]
We are experiencing significant delays in the loading times of PDF documents. Our current library, react-pdf-viewer, lacks support for linearized (or progressive) loading, resulting in suboptimal performance.

To enhance the user experience, we need to identify and integrate a PDF rendering solution that supports linearized loading. This approach will allow users to begin viewing a PDF after only the first page has loaded, rather than waiting for the entire document to download.

The following steps will be taken to address this issue:

1. Research and evaluate alternative PDF libraries compatible with our tech stack that offer linearized loading capabilities.
2. Benchmark the performance of potential libraries against our current solution.
3. Implement the chosen library and optimize the loading strategy for rapid first-page display and efficient subsequent page loading.
4. Explore additional performance optimization techniques, such as caching, pre-fetching, or utilizing service workers for background loading.

All proposed solutions should prioritize minimal disruption to the existing user interface and functionality. We welcome suggestions that can contribute to faster PDF rendering and overall performance improvements.

<sub>From [SyncLinear.com](https://synclinear.com) | [ISAAC-437](https://linear.app/isaac-editor/issue/ISAAC-437/optimize-pdf-loading-performance-by-implementing-linearized-loading)</sub>

**Comment by ologbonowiwi** [comment]
Hey @eimenhmdt, one thing that I'd like to ask... Do we upload these PDFs ourselves (they're uploaded on Isaac, or do we get the link from whatever place the user uploaded it)? Is there any way we could optimize on upload rather than download/view? 

Regarding changing the library, we likely could try [pdf.js](https://github.com/mozilla/pdf.js). Can we objectively benchmark it? (and if yes, how?) Do you recommend benchmarking it inside the project or creating a JSFiddle for comparison purposes?

I'd like to give this a shot, but I feel there is a lot to be discussed/experimented before I start to implement the actual solution

**Comment by eimenhmdt** [comment]
Hey @ologbonowiwi, thanks for your comment.

> Hey @eimenhmdt, here are a few things that I'd like to ask... Do we upload these PDFs ourselves (uploaded on Isaac, or do we get the link from wherever the user uploaded it)? Could we optimize on upload rather than download/view?
> 
Both. We have user uploaded pdfs stored in Supabase storage and load remote pdfs through a anywhere-cors proxy server.  I don't get your last question though. Could you clarify what you mean by optimising on upload?
> Regarding changing the library, we likely could try [pdf.js](https://github.com/mozilla/pdf.js). Can we objectively benchmark it? (and if yes, how?) Do you recommend benchmarking it inside the project or creating a JSFiddle for comparison purposes?
> 
tbh, the benchmarking part doesn't need to be super sophisticated. If wen can load PDFs progressively it should already be much faster than what we currently have. So, the most important metric would probably be "Time to first page render". Maybe you could compare some options to render PDFs by doing a bit of research regarding the experience of other people. Also, definitely important is how much it will add to the bundle size.

**Comment by eimenhmdt** [comment]
Ok dude, I think you're lucky. I don't know how I missed this, but it seems like react-pdf-viewer is able to implement linearisation:

https://react-pdf-viewer.dev/updates/

Should be pretty straightforward to implement. If you want to claim the bounty go for it. Otherwise, I'll close the issue.

**Comment by ologbonowiwi** [comment]
I'll work on it

**Comment by ologbonowiwi** [comment]
> Could you clarify what you mean by optimising on upload?

I suggest linearizing the documents before saving them on superbase storage.

Look at this example from a non-linearized vs. a linearized document: https://www.youtube.com/watch?v=SYnGP_BSO3c&ab_channel=Apryse%28formerlyPDFTron%29

As I did not find any flag we need to enable on react-pdf-viewer, this is likely enabled by default; what makes it work is whether the file is optimized (or not).
My suggestion for solving this is to find a way to linearize the file before we save it, and it'll load faster when a user tries to load it.

Also, on [this message](https://discord.com/channels/1085110924043616286/1178376846107217961/1181041422590279703) on discord, @mrobot-nika67 gave suggestions of other options for optimizing it.

**Comment by ologbonowiwi** [comment]
@eimenhmdt what do you have in mind to implement on this one? As linearized loading is happening already
