### ISSUE TITLE
Sign up page unable to see full page

### ISSUE THREAD

**Issue by natashaamin** [aietal/isaac#40]
<img width="1004" alt="Screenshot 2023-12-09 at 9 43 15 PM" src="https://github.com/aietal/isaac/assets/48901325/2897756c-d044-48fa-9bc1-43fce89ad385">

**Comment by eimenhmdt** [comment]
Thanks for bringing this up! On what screen size does this occur?

**Comment by eimenhmdt** [comment]
solved by #41
