### ISSUE TITLE
[ISAAC-499] Implement VS Code style onboarding screen/dashboard

### ISSUE THREAD

**Issue by eimenhmdt** [aietal/isaac#49]
we do something like this on the onboarding screen

* Highlight Isaac
* What all are the immediate actions user can start with
* What have users opened / last worked on recently
* Links to docs, guides, tutorials on Isaac, community
* Tick at the bottom or just below the recent activity to disable showing the onboarding flag

  ![image.png](https://uploads.linear.app/7c90c08b-6763-457d-8a5a-ed4ea2f3c43b/0684336f-a25a-47d5-893d-48c178573cd4/3a672f60-afb9-4625-a3df-0c65e8cf066b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdjOTBjMDhiLTY3NjMtNDU3ZC04YTVhLWVkNGVhMmYzYzQzYi8wNjg0MzM2Zi1hMjVhLTQ3ZDUtODkzZC00OGMxNzg1NzNjZDQvM2E2NzJmNjAtYWZiOS00NjI1LWEzZGYtMGM2NWU4Y2YwNjZiIiwiaWF0IjoxNzAyNDQ5MTkwLCJleHAiOjE3MDI1MzU1OTB9.V68c0Ajv6-spM6-Dmo-4gXZOXs5nCZjVpbTAy6QePM4)

<sub>From [SyncLinear.com](https://synclinear.com) | [ISAAC-499](https://linear.app/isaac-editor/issue/ISAAC-499/implement-vs-code-style-onboarding-screendashboard)</sub>

**Comment by rishi-raj-jain** [comment]
@eimenhmdt 

Please assign this to me?

**Comment by rishi-raj-jain** [comment]
@eimenhmdt

Please assign this to me?

**Comment by eimenhmdt** [comment]
done

**Comment by rajdip-b** [comment]
Hey @rishi-raj-jain would like to hop in in case you feel like!

**Comment by rishi-raj-jain** [comment]
@rajdip-b 

Nah, I'm already completing this.

**Comment by rajdip-b** [comment]
That was quick!

**Comment by rishi-raj-jain** [comment]
Thank you so much, @eimenhmdt!

I'm gonna be looking into this today to complete...
