### ISSUE TITLE
Dockerize app run

### ISSUE THREAD

**Issue by ologbonowiwi** [aietal/isaac#53]
While the steps provided on `README.md` help to run the app, it'd be easier to have a way to run it with fewer commands (preferably, `docker-compose up` would spin up everything).

This would decrease the curve for newcomers to contribute to the project.

For supabase, we can follow the steps described on [capgo](https://github.com/Cap-go/capgo/) instead of suggesting creating an account
![image](https://github.com/aietal/isaac/assets/100464352/3bc94ab2-a3a8-4974-ab26-27c3e7c0bad7)

**Comment by eimenhmdt** [comment]
Sounds good @ologbonowiwi !

Interested to work on this?

**Comment by ologbonowiwi** [comment]
Sorry for asking, but do you plan to set a bounty for this one @eimenhmdt?

**Comment by eimenhmdt** [comment]
How much do you want? 😂

**Comment by ologbonowiwi** [comment]
You tell me.
I'm kind of an outsider on this project, but IMO, this issue would bring great benefits as would improve A LOT the experience for newcomers on setup the project/making their first contribution.

**Comment by ezhil56x** [comment]
Can I take up this?
/attempt #53

**Comment by ezhil56x** [comment]
@ologbonowiwi Are you taking this?

**Comment by ologbonowiwi** [comment]
go ahead @ezhil56x

**Comment by rishi-raj-jain** [comment]
```
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public."profile" (id, email, has_seen_community_banner, editor_language)
  values (new.id, new.email, false, "English");
  return new;
end;
$$
language plpgsql
security definer
set search_path = public
;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
```

fails to work, how can I get log in to work fine with local setup?

**Comment by rishi-raj-jain** [comment]
Is something still pending here?

**Comment by rishi-raj-jain** [comment]
What's left with the local setup? I'd like to get this done.

**Comment by eimenhmdt** [comment]
I'll open a new issue later today aimed at improving the contributor setup experience in general. We can discuss things over there.
