### ISSUE TITLE
Error creating SQL tables in Supabase for a fork: "ERROR:  42704: type "public.upload_processing_status" does not exist"

### ISSUE THREAD

**Issue by polooner** [aietal/isaac#54]
1. Follow the contributing guide here:
https://github.com/aietal/isaac/blob/main/README.md

2. Create a Supabase project,
3. Copy the entire Supabase SQL Editor statement:
4.Paste it, run it

ERROR:  42704: type "public.upload_processing_status" does not exist
LINE 17: create table uploads ( id uuid default uuid_generate_v4() primary key, created_at timestamp default now(), user_id uuid default uuid_generate_v4(), status public.upload_processing_status not null, citation jsonb, project_id uuid references projects (id), file_name text, custom_citation jsonb, updated_at timestamp default now(), type text, abstract text, tldr text );
                                                                                                                                                                    ^

**Comment by Player256** [comment]
Hey @polooner I went this query for this error `CREATE TYPE upload_processing_status AS ENUM ('pending', 'processing', 'completed');`

**Comment by Player256** [comment]
@eimenhmdt is this correct?

**Comment by Player256** [comment]
You may get another error regarding vector extension. To solve it, go to your database->extensions->Search vector and enable it.

**Comment by polooner** [comment]
> Hey @polooner I went with this query to solve this error :`CREATE TYPE upload_processing_status AS ENUM ('pending', 'processing', 'completed');`

Did that as well, seems to be working for now. Just curious how do the maintainers go about this. Thanks!

**Comment by eimenhmdt** [comment]
Ahh. This should be added to the README. Good catch!
