### ISSUE TITLE
[ISAAC-503] Fix streaming on Vercel

### ISSUE THREAD

**Issue by eimenhmdt** [aietal/isaac#68]
Since deploying the app on Vercel streaming doesn’t work anymore. This is related to the streaming using the Python API, ie the openai calls.

<sub>From [SyncLinear.com](https://synclinear.com) | [ISAAC-503](https://linear.app/isaac-editor/issue/ISAAC-503/fix-streaming-on-vercel)</sub>

**Comment by rishi-raj-jain** [comment]
@eimenhmdt 

May you assign me this?

**Comment by eimenhmdt** [comment]
@rishi-raj-jain done
