### ISSUE TITLE
[ISAAC-504] Create a Unified Bash Script for Streamlined Dev Setup and Database Seeding

### ISSUE THREAD

**Issue by eimenhmdt** [aietal/isaac#88]
Objective: Simplify and enhance the onboarding process for new contributors by consolidating the entire development setup into a single, executable bash script.

Key Tasks:

1. Develop a bash script that automates the current development setup process, ensuring a seamless and efficient setup experience for new contributors.
2. Include database seeding functionality within the script to populate the database with initial data, making the initial interaction with the project more engaging and representative of a live environment.

Expected Outcome: A more streamlined and welcoming onboarding process, reducing initial setup time and complexity, and providing a better first impression of the development environment

<sub>From [SyncLinear.com](https://synclinear.com) | [ISAAC-504](https://linear.app/isaac-editor/issue/ISAAC-504/create-a-unified-bash-script-for-streamlined-dev-setup-and-database)</sub>

**Comment by ShaneMaglangit** [comment]
Hey @neo773, I see that you're already working on this. I've already created the setup script in the linked PR above, you'll only need to add the seed data now (feel free to claim the bounty)

**Comment by eimenhmdt** [comment]
Hey @ShaneMaglangit, that's awesome. Thank you! I think we should definitely split the bounty then. 

I'm going to merge Shane's PR now. How's your progress with regards to the seed data @neo773 ?

**Comment by ezhil56x** [comment]
By default SQL migrations will be applied, there is no need to seed I hope

**Comment by neo773** [comment]
> Hey @ShaneMaglangit, that's awesome. Thank you! I think we should definitely split the bounty then.
> 
> I'm going to merge Shane's PR now. How's your progress with regards to the seed data @neo773 ?

My bash script was ready but I'm stuck on the seed part, also left some notes on the Discord channel

**Comment by eimenhmdt** [comment]
@neo773 this PR #91 should resolve the issue you mentioned on Discord regarding the user profile creation. Lmk whether it works for you.
