### ISSUE TITLE
[ISAAC-505] Move the protected routes logic into a middleware

### ISSUE THREAD

**Issue by eimenhmdt** [aietal/isaac#89]
Currently, our application relies on the `useAuthRedirect` hook and react context to manage access to protected routes and manage user session. This approach is not fully capitalizing on Next.js capabilities. Our goal is to move this logic into middleware for more efficient and idiomatic handling within the Next.js framework.

<sub>From [SyncLinear.com](https://synclinear.com) | [ISAAC-505](https://linear.app/isaac-editor/issue/ISAAC-505/move-the-protected-routes-logic-into-a-middleware)</sub>

**Comment by rishi-raj-jain** [comment]
Can I be assigned this>

**Comment by rishi-raj-jain** [comment]
@eimenhmdt

Which routes would you want to be protected? Right now I see `useAuthRedirect` inside `EditorLayout` and `EditorLayout` is only used in `pages/editor/index.tsx`.

**Comment by eimenhmdt** [comment]
Atm it's just the editor route (we only have the landing page and the editor route), but it should be easily extensible.

**Comment by rishi-raj-jain** [comment]
Cool, on it ✨
