### ISSUE TITLE
[ISAAC-506] Migrate from React Query v3 to TanStack Query v5

### ISSUE THREAD

**Issue by eimenhmdt** [aietal/isaac#96]
We're currently still using React Query v3.39.2 and need to update to TanStack Query v5. 

There is a migration guide:

[https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-v5](https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-v5)

<sub>From [SyncLinear.com](https://synclinear.com) | [ISAAC-506](https://linear.app/isaac-editor/issue/ISAAC-506/migrate-from-react-query-v3-to-tanstack-query-v5)</sub>

**Comment by dotarjun** [comment]
/attempt 96 
Can I be assigned?
